name: Deploy to server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to main branch
        if: github.ref == 'refs/heads/main'
        run: |
          ssh user@server 'cd /path/to/main/branch && git pull origin main && npm install && npm run start'

      - name: Deploy to develop branch
        if: github.ref == 'refs/heads/develop' && github.event.pull_request.merged == true
        run: |
          ssh user@server 'cd /path/to/develop/branch && git pull origin develop && npm install && npm run start'
