name: GitHub-Actions
on:
  push: 
    branches: dev
  pull_request:
    branches: master
jobs:
  development:
    runs-on: ubuntu-latest
    steps:
          # Actions от github: проверяет репозиторий, гит и т.д.
          - uses: actions/checkout@v3

          # Пример однолинейного простого скрипта shell
          - name: Run a one-line script
            run: echo Hello, world!

          # Пример многолинейного скрипта shell
          - name: Run a multi-line script
            run: |
                echo Add other actions to build,
                echo test, and deploy your project.
